In [2]:
import torch
print(torch.__version__)

1.8.1+cpu


In [1]:
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib as plt

In [5]:
import torch
import numpy as np

In [7]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [15]:
x_ones = torch.ones_like(x_data)
print(f"{x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"{x_rand}")

tensor([[1, 1],
        [1, 1]])
tensor([[0.1674, 0.8473],
        [0.0205, 0.6669]])


In [19]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.6806, 0.1148, 0.0119],
        [0.3089, 0.5617, 0.3269]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [22]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor of tensor: cpu


In [31]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
    tensor = tensor.to('cuda') 

False


In [32]:
tensor = torch.ones(4, 4)
print(tensor[0])
print(tensor[:, 0])
print(tensor[..., -1])
tensor[:, 1] = 0
print(tensor)

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [33]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [40]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [41]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [43]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))
agg

12.0 <class 'float'>


tensor(12.)

In [44]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [46]:
t = torch.ones(5)
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [51]:
t.add_(1)
print(t)
print(n)

tensor([6., 6., 6., 6., 6.])
[6. 6. 6. 6. 6.]


In [52]:
n = np.ones(5)
t = torch.from_numpy(n)

In [54]:
np.add(n, 1, out=n)
print(n)
print(t)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
