In [3]:
import torch
from torch import nn
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda

In [4]:
ds = datasets.FashionMNIST(
    root='data',
    train=True,
    download=False,
    transform=ToTensor(),
    target_transform=Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1))
)

In [5]:
ds

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()
Target transform: Lambda()

In [6]:
ds[0]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0000, 0.0510,
           0.2863, 0.0000, 0.0000, 0.0039, 

In [7]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [8]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [9]:
class NeuralNetwork (nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
            nn.ReLU(),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [10]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)


In [11]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(X[0][0])
print(f"{y_pred}")



tensor([0.4067, 0.4544, 0.7622, 0.9449, 0.0156, 0.9047, 0.6339, 0.9789, 0.0843,
        0.2391, 0.5314, 0.7521, 0.8728, 0.6221, 0.1550, 0.4621, 0.7222, 0.5979,
        0.3979, 0.6774, 0.1251, 0.7445, 0.8650, 0.2837, 0.3085, 0.3991, 0.0969,
        0.0569])
tensor([6])


In [18]:
input_image = torch.rand(3, 28, 28)
print(input_image.size())



torch.Size([3, 28, 28])


In [19]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
flat_image.size()

torch.Size([3, 784])

In [20]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [21]:
print(hidden1[0])
hidden1 = nn.ReLU()(hidden1)

tensor([ 0.1615,  0.0334,  0.2253,  0.7985, -0.2056,  0.1491, -0.7368,  0.1860,
        -0.2253, -0.7724,  0.1219, -0.0956, -0.0683, -0.2507,  0.1653, -0.8866,
         0.3392,  0.1629, -0.5039,  0.1070], grad_fn=<SelectBackward>)


In [22]:
hidden1

tensor([[0.1615, 0.0334, 0.2253, 0.7985, 0.0000, 0.1491, 0.0000, 0.1860, 0.0000,
         0.0000, 0.1219, 0.0000, 0.0000, 0.0000, 0.1653, 0.0000, 0.3392, 0.1629,
         0.0000, 0.1070],
        [0.0580, 0.0000, 0.6823, 0.5840, 0.0000, 0.1756, 0.0000, 0.6283, 0.0000,
         0.0000, 0.0287, 0.0229, 0.0000, 0.0000, 0.1894, 0.0000, 0.1394, 0.3716,
         0.0000, 0.0062],
        [0.3897, 0.0000, 0.2996, 0.8167, 0.0000, 0.0000, 0.0000, 0.3884, 0.0000,
         0.0000, 0.3646, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0196, 0.3551,
         0.0000, 0.0000]], grad_fn=<ReluBackward0>)

In [23]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)

In [24]:
logits

tensor([[-0.2902, -0.0938, -0.3343,  0.2229,  0.2031,  0.0899,  0.3282, -0.0773,
         -0.0352, -0.0233],
        [-0.1003, -0.0874, -0.2638,  0.2623,  0.1634,  0.1053,  0.5355, -0.1190,
         -0.0707, -0.0501],
        [-0.1183, -0.0739, -0.1891,  0.1402,  0.1275,  0.1592,  0.4420, -0.0555,
         -0.0321,  0.0077]], grad_fn=<AddmmBackward>)

In [25]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [26]:
pred_probab

tensor([[0.0733, 0.0893, 0.0702, 0.1225, 0.1201, 0.1073, 0.1361, 0.0907, 0.0947,
         0.0958],
        [0.0849, 0.0860, 0.0721, 0.1220, 0.1105, 0.1043, 0.1603, 0.0833, 0.0874,
         0.0893],
        [0.0840, 0.0878, 0.0782, 0.1087, 0.1074, 0.1108, 0.1470, 0.0894, 0.0915,
         0.0952]], grad_fn=<SoftmaxBackward>)

In [28]:
print(model)

for name, param in model.named_parameters():
    print(f"{name} | {param.size()} | {param[: 2]}\n")

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)
linear_relu_stack.0.weight | torch.Size([512, 784]) | tensor([[ 0.0347, -0.0341, -0.0116,  ..., -0.0146,  0.0272,  0.0338],
        [-0.0271,  0.0260,  0.0076,  ...,  0.0002,  0.0239, -0.0191]],
       grad_fn=<SliceBackward>)

linear_relu_stack.0.bias | torch.Size([512]) | tensor([-0.0070,  0.0276], grad_fn=<SliceBackward>)

linear_relu_stack.2.weight | torch.Size([512, 512]) | tensor([[-0.0176, -0.0134, -0.0355,  ...,  0.0364,  0.0362,  0.0412],
        [-0.0395,  0.0372, -0.0367,  ...,  0.0343,  0.0070,  0.0110]],
       grad_fn=<SliceBackward>)

linear_relu_stack.2.bias | torch.Size([512]) | tensor([-0.0283, -0.0342], grad_fn=<SliceBackward>)

linear_re